version: '3.7'

services: 
    mysql:
        image: mysql:latest
        container_name: my_mysql
        restart: always
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_DATABASE: social-media
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: my_phpmyadmin
        links:
            - mysql
        environment: 
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports: 
            - 8000:80
    app:
        build: .
        container_name: my_app
        depends_on:
            - mysql
            - phpmyadmin
        ports:
            - 5050:80
        volumes:
            - ./src:/var/www/html/ 